### ISSUE TITLE
When the sourceended event fired, an error occur.

### ISSUE THREAD

**Issue by benvirus** [videojs/videojs-contrib-media-sources#114]
After the commit  3f9fbab207851512f8ccce17c6135f4ed5dab97a on 3 Oct 2016 , the sourceended event was added . A error occured when the sourceended was fired. 

![image](https://cloud.githubusercontent.com/assets/13535932/19954876/81fd9b94-a1b7-11e6-815c-3a1d3aae9e69.png)

![image](https://cloud.githubusercontent.com/assets/13535932/19954885/91726730-a1b7-11e6-9e62-d6ee49c605f5.png)

Can you tell me how to deal with this ? Or offer a patch .
Looking for your repley.

**Comment by forbesjo** [comment]
4.0.3+ should have this fixed, which version of this project are you using?

**Comment by benvirus** [comment]
@forbesjo We are using 3.3.1 .Thank you very much for  your repley.
