### ISSUE TITLE
Changing Flash bitrate?

### ISSUE THREAD

**Issue by Stolzenhain** [videojs/videojs-contrib-media-sources#125]
If I read the commits correctly, the `BYTES_PER_SECOND_GOAL` option (as documented in the readme) does no longer exist since [commit 747957a5bb8d9f3d6365c82d0adbb9ef6753675a](/videojs/videojs-contrib-media-sources/commit/747957a5bb8d9f3d6365c82d0adbb9ef6753675a#diff-6ad83a574b56c1ab99382182d8e8860eL135).

quoting `flash-constants.js`:
> This gives a theoretical maximum rate of 1MB/s into Flash.

Is there currently any way to handle adaption of larger bitrates / older machines for the Flash tech or can we simply assume a bitrate point at which the Flash tech becomes unusable no matter what config?

**Comment by forbesjo** [comment]
In our ABR for videojs-contrib-hls and VHS we use a throughput metric to determine if a given bitrate in Flash is causing frames to drop. We've definitely seen this with HD content so I think we can assume that Flash can't handle these larger bitrates well especially on older machines
