### ISSUE TITLE
PIPELINE_ERROR_DECODE in chrome

### ISSUE THREAD

**Issue by amanea** [videojs/videojs-contrib-media-sources#153]
Hello,

I have some websocket mp2t packets that I feed to videojs-contrib-media-sources and it produces a workable stream that displays in Chrome on windows 10.  This works well for a few minutes until I get the following error in the chrome://media internals:

Timestamp | Property | Value
-- | -- | --
00:00:00 00 | pipeline_state | kCreated
00:00:00 00 | event | WEBMEDIAPLAYER_CREATED
00:00:00 00 | url | blob:http://127.0.0.1:8080/1e26c9d5-4464-4392-9fc9-ef5b98f6e0e6
00:00:00 00 | pipeline_state | kStarting
00:00:00 15 | duration | unknown
00:00:11 374 | found_video_stream | true
00:00:11 374 | video_codec_name | h264
00:00:11 375 | debug | Video rendering in low delay mode.
00:00:11 396 | video_dds | false
00:00:11 396 | video_decoder | GpuVideoDecoder
00:00:11 396 | pipeline_state | kPlaying
00:00:11 416 | video_buffering_state | BUFFERING_HAVE_ENOUGH
00:00:11 416 | height | 480
00:00:11 416 | width | 640
00:00:11 416 | pipeline_buffering_state | BUFFERING_HAVE_ENOUGH
00:00:11 416 | event | PLAY
00:00:21 501 | video_dds | false
00:00:21 501 | video_decoder | FFmpegVideoDecoder
00:18:27 459 | debug | FFmpegVideoDecoder: avcodec_decode_video2(): Invalid data found when processing input, at timestamp: 1096208288 duration: 0 size: 298 side_data_size: 0 is_key_frame: 0 encrypted: 0 discard_padding (ms): (0, 0)
00:18:27 459 | error | video decode error
00:18:27 493 | pipeline_error | PIPELINE_ERROR_DECODE
00:18:27 493 | pipeline_state | kStopping
00:18:27 494 | pipeline_state | kStopped
00:18:27 499 | event | PAUSE

Here is how I add the Source Buffer:
` self.sourceBuffer = self.mediaSource.addSourceBuffer('video/mp2t; codecs="vp9,aac"'); `

And here is how I add the packets:
`this.sourceBuffer.appendBuffer.call(this.sourceBuffer, sliceOfVideo); `

Has anyone seen this before or have any hints on what the problem might be?  Any help you really be appreciated!!!

Thanks,
Alex. Manea

**Comment by xubinxian** [comment]
Same problem occurred in my project. Guess something runs abnormally with decoder in Chrome. Waiting for solution.

**Comment by gesinger** [comment]
Hey @amanea and @xubinxian , these problems can be from a bunch of different causes. Do you happen to have sources available to test with? Thanks.
