### ISSUE TITLE
Sample page is out-of-date

### ISSUE THREAD

**Issue by shdxiang** [videojs/videojs-contrib-media-sources#177]
With following steps:

```
git clone git@github.com:videojs/videojs-contrib-media-sources.git
cd videojs-contrib-media-sources
npm install
http-server
```

Then open http://127.0.0.1:8080/ with Chrome or Safari, I got the error in Javascript console:

> VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media.  

The other question is at line 55 of `index.html`: https://github.com/videojs/videojs-contrib-media-sources/blob/master/index.html#L55

```
sourceBuffer.appendBuffer(bytes, video);
```

I can not find where the variable `video` is defined?

Any help? Thanks~

**Comment by shdxiang** [comment]
And line 55 of `index.html`: https://github.com/videojs/videojs-contrib-media-sources/blob/master/index.html#L55

```
sourceBuffer.appendBuffer(bytes, video);
```

Where is the variable `video` defined?

**Comment by gesinger** [comment]
Hey @shdxiang, I think our sample page there is a bit out-of-date. The `appendBuffer` function only takes a single parameter (the `bytes`).

We should fix that up, however, this project is also in the process of being deprecated. We've moved relevant logic into https://github.com/videojs/http-streaming and are doing more active development there.

**Comment by shdxiang** [comment]
Thanks for reply @gesinger
