### ISSUE TITLE
Undefined sortedSegments.audio.initSegments 

### ISSUE THREAD

**Issue by gaxunil** [videojs/videojs-contrib-media-sources#181]
Hi!
We are using videojs-contrib-media-sources via videojs-contrib-hls under the VideoJS player to play HLS.

We are seeing errors from here:
https://github.com/videojs/videojs-contrib-media-sources/blob/master/src/virtual-source-buffer.js#L673

Where `this.audioBuffer_` is present (truthy) but `sortedSegments.audio.initSegment` is undefined.  So the line linked above blows up trying to access `sortedSegments.audio.initSegment.byteLength`.
`sortedSegments.audio` is present but `initSegment` is undefined.

Our use case requires multiple players on the page and sometimes in lower bandwidth locations.  
I'm pretty familiar with videojs, but pretty new to the hls-contrib arena and this repo.

What might it mean if  `this.audioBuffer_` is present but `sortedSegments.audio.initSegment` is undefined?  Could this happen in low bandwidth situations where requests for data may take longer or fail?
Any known issues with multiple players on a page?

I don't have a super consistent way to reproduce this yet, it just happens sometimes when we have multiple players on a page and when it does happen, it essentially kills the player.

I'm happy to submit a PR to just guard against the undefined `sortedSegments.audio.initSegment`, but I wanted to ask / get input first?

Thanks!

**Comment by gesinger** [comment]
Hey @gaxunil , thanks for reporting! It is possible to encounter a case like this if the video you are playing has audio (therefore, the audio buffer was set up), but the segment that is being processed doesn't have any audio in it. To verify, would you be able to set up a [reduced test case](https://css-tricks.com/reduced-test-cases/) with your source and steps to reproduce? We have a [starter template](http://jsbin.com/vokipos/8/edit?html,output) on JSBin you can use. Thanks.
