### ISSUE TITLE
Cannot read property 'EventTarget' of undefined

### ISSUE THREAD

**Issue by goatandsheep** [videojs/videojs-contrib-media-sources#182]
At line 1173, I'm getting a console error: `Uncaught TypeError: Cannot read property 'EventTarget' of undefined`

```javascript
import videojsContribMediaSources from "videojs-contrib-media-sources/dist/videojs-contrib-media-sources";

import videojs from "video.js";
videojs.registerPlugin(
  "videojs-contrib-media-sources",
  videojsContribMediaSources
);
```

* OS: MacOS
* Framework: Vue

**Comment by gesinger** [comment]
Hey @goatandsheep , judging by the import from the dist dir (which isn't committed to the repo), and EventTarget being a property of videojs, this probably has to do with your build setup. Specifically, since videojs is often treated as a global, it's probably undefined within some scope of your build (if the modules scoped separately, and videojs isn't available as a global).

**Comment by goatandsheep** [comment]
The reason why I imported from dist is because if I import directly, i.e.

```javascript
import videojsContribMediaSources from "videojs-contrib-media-sources";

import videojs from "video.js";
window.videojs = videojs;

videojs.registerPlugin(
  "videojs-contrib-media-sources",
  videojsContribMediaSources
);
```

I get `Error: Illegal plugin for "videojs-contrib-media-sources", must be a function, was undefined`

**Comment by gkatsev** [comment]
videojs-contrib-media-sources isn't really a plugin, in addition, the `dist` file expects `videojs` to be available globally.
It adds `MediaSource` and `URL` properties to `videojs`.

**Comment by gkatsev** [comment]
Were you able to get it working?

**Comment by goatandsheep** [comment]
Not yet. I'm still working on it right now

**Comment by goatandsheep** [comment]
I'm still trying to figure out how to import the "add-on".

**Comment by goatandsheep** [comment]
The solution is: simply import and don't register it as a plugin. Also, import the add-on after you import `videojs`.

```javascript
import "videojs"
import "videojs-contrib-media-sources"
```
