### ISSUE TITLE
Player will not start with video.js v7.2.4

### ISSUE THREAD

**Issue by enzanki-ars** [videojs/videojs-contrib-media-sources#184]
* [Segments load and play without using video.js](https://github.com/enzanki-ars/eAVFD-test-01/tree/master/)
* [Segments load and play with video.js v6.12.0](https://github.com/enzanki-ars/eAVFD-test-01/tree/video-js-verison-v6_12_0)
* [Segments do not load and play with video.js v7.2.4 - no error messages displayed](https://github.com/enzanki-ars/eAVFD-test-01/tree/video-js-version-v7_2_4)

Code that I use to test is linked above.  Not sure if this plugin is still compatible with v7+.

**Comment by forbesjo** [comment]
Have you tried using your test code with video.core.js (https://unpkg.com/video.js@7.3.0/dist/alt/video.core.js) ? The video.js 7 main build has VHS built in which may affect contrib-media-sources

**Comment by forbesjo** [comment]
Thank you for your issue but we will not be accepting new changes for this repo and it will be [archived](https://help.github.com/articles/about-archiving-repositories/) very soon. I would advise you to open your PR against the next iteration of videojs-contrib-hls at https://github.com/videojs/http-streaming if you are still experiencing issues.
