### ISSUE TITLE
mark more tags as releases?

### ISSUE THREAD

**Issue by pennello** [videojs/videojs-contrib-media-sources#21]
I was playing around with the MSE plugin recently, and kept running into an issue where one of my source buffers was missing the `abort` method.  I finally realized that I had just clicked through on the release next to "latest release" in the releases area of the GitHub page, and thus was using version 0.1.0.  The `README.md`, though, mentions 0.2.0 and 0.3.0 as release, though they're not marked as such.  Could it be helpful to mark these tags as actual releases on the GitHub UI?

**Comment by gkatsev** [comment]
Sure. Makes sense.

**Comment by gkatsev** [comment]
Done.

**Comment by pennello** [comment]
Nice; thanks!
