### ISSUE TITLE
DASH Doesn't Work

### ISSUE THREAD

**Issue by up4** [videojs/videojs-contrib-media-sources#26]
I'm assuming this plugin is supposed to eventually replace Dash.js' Video.js plugin (which has not been updated for a while) but I actually don't know if it is supposed to even support DASH at all (this repository's "dash" directory is 2yo. So wild guess here.

I'm trying to have Video.js ingest various DASH264 MPDs on Mac OS X 10.10.3, Apple Safari 8.0.6 and of course it doesn't work. Is this the right place to start to *make* it work?

Regards,

Vincent

**Comment by imbcmdth** [comment]
videojs-contrib-hls was never designed to support DASH playback. That old `dash` directory was something left over from an old (very old) experiment that should not have been included in the master branch. The directory will be removed in the next release.

If you need DASH support, the plugin in the `contrib` directory of Dash.js has been recently updated and should support Video.js 5.

**Comment by up4** [comment]
Ok thanks for the precision.
