### ISSUE TITLE
Request to add this plugin to bower an npm

### ISSUE THREAD

**Issue by carpasse** [videojs/videojs-contrib-media-sources#27]
I would like to request that we add this plugin to bower and npm to ease the dependency management.

Well technically speaking the plugin is already on npm, but I am missing a bin folder with the "compiled" version of the plugin.

**Comment by gkatsev** [comment]
This plugin doesn't really require any compilation. It the "prod" version is available in `src/`.
At some point, we'll transition to use babel+browserify so everything can be pulled in via commonjs/es6 imports.

**Comment by carpasse** [comment]
I guess you are right I was thinking on the possibility of offering a minified version and a UMD version like you are doing with the video-contrib-ads.

Regarding bower, do you have any plan into adding this plugin to bower?

**Comment by dcrockwell** [comment]
+1 for npm and bower. It's a de facto standard to publish software via package manager these days.

**Comment by forbesjo** [comment]
We are not planning on publishing this plugin to bower, just npm.
