### ISSUE TITLE
b64str should be declared

### ISSUE THREAD

**Issue by khejing** [videojs/videojs-contrib-media-sources#28]
I use videojs-contrib-media-sources with webpack, and compile it with Babel. Babel use strict mode by default, so videojs-media-sources.js will throw an exception in browser, just because b64str has not been declared. For now I can use imports-loader to declare b64str in webpack config file, but I think it should be fixed, right?

**Comment by gkatsev** [comment]
Oops. It should definitely be declared. Want to submit a PR for it?
