### ISSUE TITLE
exception when using videojs-contrib-hls to play hls in chrome

### ISSUE THREAD

**Issue by schbook** [videojs/videojs-contrib-media-sources#38]
exception throws when using videojs-contrib-hls to play hls in chrome which shows as follow:
Uncaught InvalidStateError: SourceBuffer.append() cannot be called while an update is in progress

the environment is chrome in mac os x, but the video.js player still works right under this exception

**Comment by imbcmdth** [comment]
Thanks for the issue, @schbook. We've made many changes and enhancement since this was opened. Do you still see this issue with the latest pre-release?
