### ISSUE TITLE
Fix link on npmjs.com repository

### ISSUE THREAD

**Issue by DJLebedev** [videojs/videojs-contrib-media-sources#42]
Please, fix link to you project on repository npmjs.com. Now you have link "github.com/videojs/video-js-media-sources". But that must been "github.com/videojs/videojs-contrib-media-sources".
I can not do `composer require npm-asset/videojs-contrib-media-sources` because package not found.

**Comment by forbesjo** [comment]
npm has the correct url at the moment, closing
