### ISSUE TITLE
Should MediaSources input work with Flash tech?

### ISSUE THREAD

**Issue by norlin** [videojs/videojs-contrib-media-sources#49]
Hi,

I'm trying to use MediaSources input with Flash tech and it seems it doesn't work in latest versions in Chrome browser... (With `master` version all seems ok.)

Here is an example: http://jsbin.com/pepifanihe/3

As you see, browser trying to download url `blob:http%3A//output.jsbin.com/570ed825-77de-4bed-9917-3b92e09889ff` instead of waiting for MediaSource data.

For Html5 tech all works good.

Is there anything wrong with my code or it's a bug?

p.s. note, there is no video link, so video won't play in any case, but I'm talking about browser's attempt to download `blob:...` url.

**Comment by norlin** [comment]
The thing is videojs.MediaSource creates native MediaSource object even for Flash tech, by default (when no "mode" option).

Also I have faced with other thing even for mode: "flash", but still debugging it.

**Comment by norlin** [comment]
One more question – about FlashMediaSource – as it judging by code, it's only accept mp2t video. What about other types like flv, mp4, etc...?

**Comment by forbesjo** [comment]
contrib-media-sources only accepts mp2ts because that is the only thing that we are able to transmux into flv tags. If you want to support other formats you must add the ability to transmux them into mux.js (https://github.com/videojs/mux.js).
