### ISSUE TITLE
FLV codec support h.264 and mp3.

### ISSUE THREAD

**Issue by heff** [videojs/videojs-contrib-media-sources#8]
According to this page at least.
https://app.zencoder.com/docs/api/encoding/format-and-codecs/format

The FLV codec regex should probably be updated to support that.

**Comment by albertyw** [comment]
I'm a bit confused by your link to the Zencoder website.  What does VideoJS playback have to do with Zencoder?

Also, I've gotten test videos (flv/h264/mp3) to work correctly with MSE.  I believe I did have to break some Content-Type validation code, but the playback is fine.  I'll comment back when I have specifics.

**Comment by heff** [comment]
Glad to hear you got it working! The zencoder site was just a point of reference to verify that the FLV container does in fact allow the h264 and mp3 codecs.
